services:
  mysql:
    image: mysql:8.0
    container_name: urlshortener-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: urlshortener
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: urlshortener-redis
    restart: always
    ports: 
      - "6379:6379"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: urlshortener-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  api:
    build: .
    container_name: urlshortener-api
    restart: always
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: server=mysql;port=3306;database=urlshortener;user=root;password=rootpassword

volumes:
  mysql_data: